### ISSUE TITLE
License, please?

### ISSUE THREAD

**Issue by MostAwesomeDude** [xtruder/kubenix-modules#75]
Hi! Please put a license on this repo. I have PRs I want to send, including chaoskube and spartakus modules. Thanks!

**Comment by offlinehacker** [comment]
License added in https://github.com/xtruder/kubenix-modules/commit/2cecb00a4cc878ba5ccb1405ee05b0ec1c5a1c4b. There's still much work to be done to improve `kubenix` and `kubenix-modules` as opensource projects. Even in this unfinished state i'm happy for all contributions :)
